version: "3.8"



services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_RUN_ONCE=${WATCHTOWER_RUN_ONCE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock